-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-12-11 14:05:48 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012

-- Drop table if they exists
IF OBJECT_ID('Vysledky', 'U') IS NOT NULL
  DROP TABLE Vysledky 
IF OBJECT_ID('Rozpis', 'U') IS NOT NULL
  DROP TABLE Rozpis 
IF OBJECT_ID('Umisteni', 'U') IS NOT NULL
  DROP TABLE Umisteni
IF OBJECT_ID('Statistiky', 'U') IS NOT NULL
  DROP TABLE Statistiky 
IF OBJECT_ID('Tresty', 'U') IS NOT NULL
  DROP TABLE Tresty 
IF OBJECT_ID('Clenove', 'U') IS NOT NULL
  DROP TABLE Clenove 
IF OBJECT_ID('Tymy', 'U') IS NOT NULL
  DROP TABLE Tymy 
IF OBJECT_ID('Adresa ', 'U') IS NOT NULL
  DROP TABLE Adresa 
IF OBJECT_ID('Mesto', 'U') IS NOT NULL
  DROP TABLE Mesto 

CREATE
  TABLE Adresa
  (
    aID   INTEGER NOT NULL ,
    psc   INTEGER NOT NULL ,
    ulice VARCHAR (100)
  )
  ON "default"
GO
ALTER TABLE Adresa ADD CONSTRAINT Adresa_PK PRIMARY KEY CLUSTERED (aID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Clenove
  (
    cID       INTEGER NOT NULL ,
    jmeno     VARCHAR (20) NOT NULL ,
    prijimeni VARCHAR (40) NOT NULL ,
    tym  	  CHAR (10) NOT NULL ,
    aID       INTEGER NOT NULL ,
    muze_hrat BIT
  )
  ON "default"
GO
ALTER TABLE Clenove ADD CONSTRAINT Clenove_PK PRIMARY KEY CLUSTERED (cID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Mesto
  (
    psc   INTEGER NOT NULL ,
    mesto VARCHAR (30) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Mesto ADD CONSTRAINT Mesto_PK PRIMARY KEY CLUSTERED (psc)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Rozpis
  (
    zID    INTEGER NOT NULL ,
    domaci CHAR (10) NOT NULL ,
    hoste  CHAR (10) NOT NULL ,
    datum  DATETIME2 NOT NULL ,
    odehrano BIT
  )
  ON "default"
GO
ALTER TABLE Rozpis ADD CONSTRAINT Rozpis_PK PRIMARY KEY CLUSTERED (zID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Statistiky
  (
    cID             INTEGER NOT NULL ,
    pozice          CHAR (1) NOT NULL ,
    goly            INTEGER NOT NULL ,
    asistence       INTEGER NOT NULL ,
    pozitivni_ucast INTEGER NOT NULL ,
    negativni_ucast INTEGER NOT NULL ,
    trestne_minuty  INTEGER
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Statistiky__IDX ON Statistiky
(
  cID
)
ON "default"
GO
ALTER TABLE Statistiky ADD CONSTRAINT Statistiky_PKv1 PRIMARY KEY CLUSTERED (
cID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Tresty
  (
    tID INTEGER NOT NULL ,
    cID INTEGER NOT NULL ,
    od DATETIME2 NOT NULL ,
    do DATETIME2 NOT NULL
  )
  ON "default"
GO
ALTER TABLE Tresty ADD CONSTRAINT Tresty_PK PRIMARY KEY CLUSTERED (tID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Tymy
  (
    kod   CHAR (10) NOT NULL ,
    nazev VARCHAR (50) NOT NULL ,
    psc   INTEGER NOT NULL
  )
  ON "default"
GO
ALTER TABLE Tymy ADD CONSTRAINT Tymy_PK PRIMARY KEY CLUSTERED (kod)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Umisteni
  (
    kod                CHAR (10) NOT NULL ,
    zapasy             INTEGER NOT NULL ,
    vyhry              INTEGER NOT NULL ,
    vyhry_prodlouzeni  INTEGER NOT NULL ,
    prohry_prodlouzeni INTEGER NOT NULL ,
    prohry             INTEGER NOT NULL ,
    vstrelene_goly      INTEGER NOT NULL ,
    obdrzene_goly      INTEGER NOT NULL ,
    body               INTEGER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Umisteni__IDX ON Umisteni
(
  kod
)
ON "default"
GO
ALTER TABLE Umisteni ADD CONSTRAINT Umisteni_PK PRIMARY KEY CLUSTERED (kod)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Vysledky
  (
    zID         INTEGER NOT NULL ,
    domaci_goly INTEGER NOT NULL ,
    hoste_goly  INTEGER NOT NULL ,
    prodlouzeni BIT
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Vysledky__IDX ON Vysledky
(
  zID
)
ON "default"
GO
ALTER TABLE Vysledky ADD CONSTRAINT Vysledky_PK PRIMARY KEY CLUSTERED (zID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

ALTER TABLE Adresa
ADD CONSTRAINT Adresa_Mesto_FK FOREIGN KEY
(
psc
)
REFERENCES Mesto
(
psc
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Clenove
ADD CONSTRAINT Clenove_Adresa_FK FOREIGN KEY
(
aID
)
REFERENCES Adresa
(
aID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Clenove
ADD CONSTRAINT Clenove_Tymy_FK FOREIGN KEY
(
tym
)
REFERENCES Tymy
(
kod
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Rozpis
ADD CONSTRAINT Rozpis_Tymy_FK FOREIGN KEY
(
domaci
)
REFERENCES Tymy
(
kod
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Rozpis
ADD CONSTRAINT Rozpis_Tymy_FKv1 FOREIGN KEY
(
hoste
)
REFERENCES Tymy
(
kod
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Statistiky
ADD CONSTRAINT Statistiky_Clenove_FK FOREIGN KEY
(
cID
)
REFERENCES Clenove
(
cID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Tresty
ADD CONSTRAINT Tresty_Clenove_FK FOREIGN KEY
(
cID
)
REFERENCES Clenove
(
cID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Tymy
ADD CONSTRAINT Tymy_Mesto_FK FOREIGN KEY
(
psc
)
REFERENCES Mesto
(
psc
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Umisteni
ADD CONSTRAINT Umisteni_Tymy_FK FOREIGN KEY
(
kod
)
REFERENCES Tymy
(
kod
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Vysledky
ADD CONSTRAINT Vysledky_Rozpis_FK FOREIGN KEY
(
zID
)
REFERENCES Rozpis
(
zID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Adresa ADD CHECK (psc BETWEEN 10000 AND 99999);
ALTER TABLE Statistiky ADD CHECK (pozice IN ('Ú','O'));
ALTER TABLE Statistiky ADD CHECK (goly >= 0);
ALTER TABLE Statistiky ADD CHECK (asistence >= 0);
ALTER TABLE Statistiky ADD CHECK (pozitivni_ucast >= 0);
ALTER TABLE Statistiky ADD CHECK (negativni_ucast >= 0);
ALTER TABLE Statistiky ADD CHECK (trestne_minuty >= 0);
ALTER TABLE Umisteni ADD CHECK (zapasy >= 0);
ALTER TABLE Umisteni ADD CHECK (vyhry >= 0);
ALTER TABLE Umisteni ADD CHECK (vyhry_prodlouzeni >= 0);
ALTER TABLE Umisteni ADD CHECK (prohry_prodlouzeni >= 0);
ALTER TABLE Umisteni ADD CHECK (prohry >= 0);
ALTER TABLE Umisteni ADD CHECK (vstrelene_goly >= 0);
ALTER TABLE Umisteni ADD CHECK (obdrzene_goly >= 0);
ALTER TABLE Umisteni ADD CHECK (body >= 0);
ALTER TABLE Vysledky ADD CHECK (domaci_goly >= 0);
ALTER TABLE Vysledky ADD CHECK (hoste_goly >= 0);
